---
title: "Assignment 2"
author: "Junn Pham, 300538618"
date: "2023-05-04"
output:
  pdf_document: default
  html_document: default
---
When submitting my work I confirm:

* I have completed all steps of the attached assessment on my own,
* I have not used any unauthorised materials while completing this assessment, and
* I have not given anyone else access to my assessment. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Question 1**

a.

```{r}
movies<- read.csv("movies500.csv", header = TRUE)
movies_genres<- read.csv("movies500_genres.csv", header = TRUE)
genres<- read.csv("genres.csv", header = TRUE)
```

b.

```{r}
library(DBI)
library(RSQLite)
if (file.exists("movies.sqlite")) {
  unlink('movies.sqlite', recursive=TRUE)
}
movies_conn <- dbConnect(RSQLite::SQLite(), "movies.sqlite")
```

c.

```{r}
dbWriteTable(movies_conn, "movies", movies, overwrite=TRUE)
dbWriteTable(movies_conn, "movies_genres", movies_genres, overwirte=TRUE)
```

d.

```{sql connection=movies_conn}
SELECT count(*) as 'number of rows' FROM movies
```
e.

```{sql connection=movies_conn}
SELECT title, runtime, release_date FROM movies
WHERE runtime > 480
ORDER BY runtime asc
```

f.

```{sql connection=movies_conn}
SELECT title FROM movies
WHERE title LIKE '%love%'
```

g.

```{sql connection=movies_conn}
CREATE TABLE genres (
  genre_id integer,
  genre_name text
)
```

h.

```{r}
dbWriteTable(movies_conn, "genres", genres, append=TRUE)
```

i.

```{sql connection=movies_conn}
INSERT INTO genres(genre_id, genre_name)
VALUES (3579,"University Comedy")
```

j.

```{sql connection=movies_conn}
UPDATE genres 
SET genre_name="University Tragedy"
WHERE genre_id=3579
```

k.

```{sql connection=movies_conn}
SELECT movies_genres.genre_id from movies
JOIN movies_genres ON movies.tmdbId = movies_genres.tmdbId
WHERE movies.title = "Running Wild"
```

l.

```{sql connection=movies_conn}
SELECT genres.genre_name from genres
JOIN (
  SELECT * from movies
  JOIN movies_genres ON movies.tmdbId = movies_genres.tmdbId
  WHERE movies.title = "Running Wild"
) X
ON X.genre_id = genres.genre_id
```

m.

```{sql connection=movies_conn}
SELECT genres.genre_name,count(*) from genres
LEFT JOIN (
  SELECT * from movies
  JOIN movies_genres ON movies.tmdbId = movies_genres.tmdbId
) X
ON X.genre_id = genres.genre_id
GROUP BY genres.genre_id
HAVING count(*) >= 20
ORDER BY 2 DESC
```
```{r}
dbDisconnect(movies_conn)
```

**Question 2**

```{r, message=FALSE}
library(dplyr)
```

```{r}
library(tidyr)
vehicles <- read.csv("motor_vehicle_modified.csv", stringsAsFactors = FALSE)
vehicles_R <- vehicles
```

a.

```{r}
##dplyr
summarise(filter(vehicles, transmission_type=='4-gear auto' & (make=='Kia' | make=='Honda')),count=n()) 

##Base R
sum(vehicles_R$transmission_type=='4-gear auto' & (vehicles_R$make=='Kia' | vehicles_R$make=='Honda')) 
```

b.
```{r}
##dplyr
vehicles <- vehicles %>% select(-vehicle_usage, -vehicle_type)

##Base R
vehicles_R <- subset(vehicles_R, select = -c(vehicle_usage, vehicle_type))
```

c.
```{r}
##dplyr
vehicles_country_status <- vehicles %>% group_by(original_country, import_status) %>% 
                            summarise(Count=n())

##Base R
vehicles_country_status_R <- vehicles_R
vehicles_country_status_R <- aggregate(vehicles_country_status_R$original_country, by=list(vehicles_country_status_R$original_country,vehicles_country_status_R$import_status), FUN=length)
colnames(vehicles_country_status_R) <- c("original_country", "import_status", "Count")
```

d.

```{r}
##dplyr
sorted_vehicles_country_status <- filter(vehicles_country_status, import_status=='used') %>% arrange(desc(Count))  
sorted_vehicles_country_status[1:3,]

##Base R
sorted_vehicles_country_status_R <- vehicles_country_status_R[vehicles_country_status_R$import_status=="used",]
sorted_vehicles_country_status_R <- sorted_vehicles_country_status_R[order(sorted_vehicles_country_status_R$Count, decreasing = TRUE),]
head(sorted_vehicles_country_status_R,3)

```

**Question 3**


```{r}
library(ggplot2)
data(starwars)
```

a.

```{r}
filter(starwars, is.na(species)==FALSE) %>% ggplot() +
  geom_bar(aes(x=species)) +
  coord_flip() + 
  labs(x = "Species", y = "Count", title = "The number of individuals of each species")
```

b.

```{r}
starwars_species <- starwars %>% group_by(species) %>% summarise(num=n())
starwars <- full_join(starwars,starwars_species)
```

c.

```{r}
starwars <- starwars %>% mutate(Mainspecies=starwars$species) %>% 
            rows_update(tibble(num=1, Mainspecies="Other"))

```

d.

```{r}
plot.settings <- filter(starwars, is.na(Mainspecies)==FALSE & is.na(height)==FALSE & is.na(mass)==FALSE) %>% ggplot(aes(x = height, y = mass)) + 
  labs(x = "Height (cm)", y = "Weight (kg)", title = "The scatter plot of weight and height of the mainspecies") + 
  theme_classic()
plot.settings + geom_point(aes(x = height, y = mass, colour = Mainspecies), position = "jitter")
```

e.

```{r}
outlier <- arrange(starwars, desc(mass)) %>% head(1)

select(outlier, name, height, mass, species)

plot.settings <- anti_join(starwars,outlier) %>% filter(is.na(Mainspecies)==FALSE & is.na(height)==FALSE & is.na(mass)==FALSE) %>% 
  ggplot(aes(x = height, y = mass)) + 
  labs(x = "Height (cm)", y = "Weight (kg)", title = "The scatter plot of weight and height of the mainspecies") + 
  theme_classic()
plot.settings + geom_point(aes(x = height, y = mass, colour = Mainspecies), position = "jitter")
```

f.

```{r}
plot.settings <- filter(starwars, (species == "Human" | species == "Droid") & is.na(height)==FALSE & is.na(mass)==FALSE) %>% ggplot( aes(x = height, y = mass)) + 
  labs(x = "Height (cm)", y = "Weight (kg)") + 
  theme_classic()
plot.settings + 
  geom_point(aes(x = height, y = mass), position = "jitter") + 
  facet_wrap(~species) + 
  geom_smooth(method = "lm")

```

g.

```{r}
filter(starwars, is.na(Mainspecies)==FALSE & is.na(height)==FALSE) %>% ggplot() + 
  geom_boxplot(aes(x = Mainspecies, y = height)) + 
  labs(x="Mainspecies", y="Height (cm)", title = "Boxplots of height of each mainspecies")

```

h.

```{r}
filter(starwars, is.na(Mainspecies)==FALSE) %>% ggplot() +
  geom_bar(aes(x = Mainspecies, fill = eye_color), position = "fill") +
  coord_flip() + 
  labs(x = "Mainspecies", y = "Proportion",fill = "Eye colors", title = "The proportions of the various eye colours within each mainspecies")
            
```

